name: Lint documentation

on:
  workflow_call:
    inputs:
      mdl:
        required: false
        type: boolean
        default: true
      mdl-path:
        required: false
        type: string
        default: CHANGELOG.md README.md docs
      rubocop:
        required: false
        type: boolean
        default: true
      rubocop-gemfile:
        required: false
        type: string
        default: gemfiles/rubocop.gemfile
      forspell:
        required: false
        type: boolean
        default: true
      forspell-args:
        required: false
        type: string
        default: "**/*.md *.md"
      lychee:
        required: false
        type: boolean
        default: true
      lychee-args:
        required: false
        type: string
        default: docs/* README.md CHANGELOG.md

jobs:
  markdownlint:
    if: ${{ inputs.mdl }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1
    - name: Run Markdown linter
      run: |
        gem install mdl
        mdl ${{ inputs.mdl-path }}

  rubocop:
    if: ${{ inputs.rubocop }}
    runs-on: ubuntu-latest
    env:
      BUNDLE_GEMFILE: ${{ inputs.rubocop-gemfile }}
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1
        bundler-cache: true
    - name: Lint Markdown files with RuboCop
      run: |
        bundle exec rubocop -c .rubocop-md.yml

  forspell:
    if: ${{ inputs.forspell }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Hunspell
      run: |
        sudo apt-get install hunspell
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1
    - name: Cache installed gems
      uses: actions/cache@v1
      with:
        path: /home/runner/.rubies/ruby-2.7.0/lib/ruby/gems/2.7.0
        key: gems-cache-${{ runner.os }}
    - name: Install Forspell
      run: gem install forspell
    - name: Run Forspell
      run: forspell ${{ inputs.forspell-args }}

  lychee:
    if: ${{ inputs.lychee }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Link Checker
      id: lychee
      uses: lycheeverse/lychee-action@v1.5.1
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      with:
        args: ${{ inputs.lychee-args }}
